name: beba_driver
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_bottom_navigation_bar: ^1.3.3

  board_datetime_picker: ^2.1.3

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.4.0

  fl_country_code_picker: ^0.1.9+1
  flutter_dash: ^1.0.0
  flutter_dotenv: ^5.2.1
  flutter_easyloading: ^3.0.5
  flutter_polyline_points: ^2.1.0
  flutter_rating_stars: ^1.1.0
  flutter_svg: ^2.0.16

  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  google_places_flutter: ^2.0.9
  google_fonts: ^6.2.1
  google_maps_flutter_platform_interface: ^2.9.2
  google_maps_flutter_android: ^2.14.10
  geocoder3:
    git:
      url: https://github.com/rennylangat/geocoder3.git
  get_secure_storage: ^1.0.5

  intl: ^0.19.0
  in_app_update: ^4.2.3

  location: ^7.0.1

  material_design_icons_flutter: ^7.0.7296

  pin_code_fields: ^8.0.1

  simple_animations: ^5.1.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  shimmer: ^3.0.0
  slide_action: ^0.0.2
  dio: ^5.7.0
  device_info_plus: ^11.2.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Condensed.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 800
